site_name: Demo Docs
site_description: Documentation for the demo project
theme: readthedocs
pages:
- Index: 'index.md'
- JavaScript Project Components:
  - script: 'script.md'
  - interface: interface.md
  - strom_client: 'strom_client.md'
  - Map: 'Map.md'
  - Trip: 'Trip.md'
  - Driver: 'Driver.md'
  - Route: 'Route.md'
